/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panal;

import control.workers_cont;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.workers_caps;
import model.workers_model;
import static view.panal.items.table;

/**
 *
 * @author Enjoy
 */
public class workers extends javax.swing.JPanel {

    /**
     * Creates new form workers
     */ArrayList a=new ArrayList();
    public workers() {
        initComponents();
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        new workers_model().show_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_time = new javax.swing.JComboBox();
        txt_code = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_notes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        image_label = new javax.swing.JLabel();
        add_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        radio_name = new javax.swing.JRadioButton();
        radio_code = new javax.swing.JRadioButton();
        txt_search = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        new_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        label_validation = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بيانات الموظف", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("الاسم ");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("رقم التليفون");

        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_phoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("تاريخ البدء");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("وقت العمل ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("المرتب");

        txt_salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_salaryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_salaryKeyReleased(evt);
            }
        });

        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_addressKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("العنوان");

        combo_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));

        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codeKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("الكود");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ملاحظــــات");

        txta_notes.setColumns(20);
        txta_notes.setRows(5);
        jScrollPane2.setViewportView(txta_notes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(combo_time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txt_salary))
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(45, 45, 45)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_code)
                    .addComponent(txt_address)
                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الصورة الشخصية", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N

        image_label.setText("الصورة الشخصية");

        add_image.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_image.setText("اضـــــافة");
        add_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_imageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_image, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_image, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاسم", "رقم التليفون", "العنوان", "المرتب", "وقت العمل", "تاريخ البدء"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("بحـــث");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        buttonGroup1.add(radio_name);
        radio_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radio_name.setSelected(true);
        radio_name.setText("الاسم");

        buttonGroup1.add(radio_code);
        radio_code.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radio_code.setText("الكود");

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/add2.png"))); // NOI18N
        add_button.setText("اضـــافة");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/10.png"))); // NOI18N
        update_button.setText("تعــديل");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        new_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/NEW.gif"))); // NOI18N
        new_button.setText("جديد");
        new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_buttonActionPerformed(evt);
            }
        });

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/delete2.png"))); // NOI18N
        delete_button.setText("حــذف");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(new_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_code)
                                .addGap(10, 10, 10)
                                .addComponent(radio_name)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radio_name)
                                .addComponent(radio_code)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed


    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_phone.requestFocusInWindow();
        }

//txt_name.setBackground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyPressed


        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_address.requestFocusInWindow();
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneKeyPressed

    private void txt_salaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salaryKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_code.requestFocusInWindow();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryKeyPressed

    private void txt_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_salary.requestFocusInWindow();
        }


    }//GEN-LAST:event_txt_addressKeyPressed

    private void txt_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txta_notes.requestFocusInWindow();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txt_codeKeyPressed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        /*............ Validation ....................*/
          workers_cont b = new workers_cont();
        String name=txt_name.getText();
        String code=txt_code.getText();
        String phone =txt_phone.getText();
        if(b.add_validation().contains(name)||b.add_validation().contains(code)||b.add_validation().contains(phone)){
            JOptionPane.showMessageDialog(null, " هذه البيانات موجودة سابقا  !!");
        }else{
        
        try {
            if (txt_name.getText().equals("") || txt_phone.getText().equals("") || txt_address.getText().equals("") || txt_salary.getText().equals("") || txt_code.getText().equals("")) {
               label_validation.setText("Error in Insert please check data !!!  ");
               label_validation.setForeground(Color.red);
            } else {

                /*........................................*/
                workers_caps obj = new workers_caps();
                //  workers_model a=new workers_model();
                //start_date.getDateEditor().getUiComponent().gett
            
                obj.setName(txt_name.getText());
                obj.setPhone(txt_phone.getText());
                obj.setStart_date(((JTextField)start_date.getDateEditor().getUiComponent()).getText());
                obj.setAddress(txt_address.getText());
                obj.setSalary(Double.parseDouble(txt_salary.getText()));
                obj.setTime(combo_time.getSelectedItem().toString());
                obj.setCode(txt_code.getText());
                obj.setNote(txta_notes.getText());
//obj.setImage;

                b.insert(obj);
                /*...................................................*/
                txt_name.setText("");
                txt_phone.setText("");
                start_date.setDateFormatString("");
                txt_salary.setText("");
                txt_address.setText("");
                txt_code.setText("");
                txta_notes.setText("");
                b.showdata();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }

    }//GEN-LAST:event_add_buttonActionPerformed

    private void new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_buttonActionPerformed
        txt_name.setText("");
        txt_phone.setText("");
        ((JTextField)start_date.getDateEditor().getUiComponent()).setText("");
        txt_salary.setText("");
        txt_address.setText("");
        txt_code.setText("");
        txta_notes.setText("");
txt_search.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_new_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
if (txt_name.getText().equals("") || txt_phone.getText().equals("") || txt_address.getText().equals("") || txt_salary.getText().equals("") || txt_code.getText().equals("")) {
               label_validation.setText("Error in delete please check data !!!  ");
               label_validation.setForeground(Color.red);
}else{
    int a=JOptionPane.showConfirmDialog(null, "هل تريد الحذف    !!");
    if(a==0){
        workers_caps obj = new workers_caps();
        obj.setCode(txt_code.getText());
        workers_cont b = new workers_cont();
        b.dalete(obj);
         txt_name.setText("");
        txt_phone.setText("");
        start_date.setDateFormatString("");
        txt_salary.setText("");
        txt_address.setText("");
        txt_code.setText("");
        txta_notes.setText("");
txt_search.setText("");
        b.showdata();
}}
// TODO add your handling code here:
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int row = table.getSelectedRow();
        String name = table.getModel().getValueAt(row, 0).toString();
        txt_name.setText(name);
        String phone = table.getModel().getValueAt(row, 1).toString();
        txt_phone.setText(phone);
        String salary = table.getModel().getValueAt(row, 2).toString();
        txt_salary.setText(salary);
        String time = table.getModel().getValueAt(row, 3).toString();
        combo_time.setSelectedItem(time);
        ((JTextField)start_date.getDateEditor().getUiComponent()).setText(table.getValueAt(row, 4).toString());
//        String date = table.getModel().getValueAt(row, 4).toString();
//        start_date.setDateFormatString(date);
        String address = table.getModel().getValueAt(row, 5).toString();
        txt_address.setText(address);
        String code = table.getModel().getValueAt(row, 6).toString();
        txt_code.setText(code);
        String notes = table.getModel().getValueAt(row, 7).toString();
        txta_notes.setText(notes);

// TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed

        workers_caps obj = new workers_caps();
        workers_cont b = new workers_cont();
        obj.setName(txt_name.getText());
        obj.setPhone(txt_phone.getText());
        obj.setStart_date(((JTextField)start_date.getDateEditor().getUiComponent()).getText());
        obj.setAddress(txt_address.getText());
        obj.setSalary(Double.parseDouble(txt_salary.getText()));
        obj.setTime(combo_time.getSelectedItem().toString());
        obj.setCode(txt_code.getText());
        obj.setNote(txta_notes.getText());
//obj.setImage;

        b.update(obj);
txt_name.setText("");
        txt_phone.setText("");
        start_date.setDateFormatString("");
        txt_salary.setText("");
        txt_address.setText("");
        txt_code.setText("");
        txta_notes.setText("");
txt_search.setText("");
        b.showdata();

//
//DefaultTableModel model = (DefaultTableModel) table.getModel();        
//int row=table.getSelectedRow();
//
//model.setValueAt(txt_name.getText(), row, 0);
//model.setValueAt(txt_phone.getText(), row, 1);
//model.setValueAt(txt_salary.getText(), row, 2);
//model.setValueAt(combo_time.getSelectedItem(), row, 3);
//model.setValueAt(start_date.getDate(), row, 4);
//model.setValueAt(txt_address.getText(), row, 5);
//model.setValueAt(txt_code.getText(), row, 6);
//model.setValueAt(txta_notes.getText(), row, 7);
// TODO add your handling code here:
    }//GEN-LAST:event_update_buttonActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
//        if (radio_name.isSelected()) {
//            workers_caps obj = new workers_caps();
//            workers_cont b = new workers_cont();
//            obj.setSearch(txt_search.getText());
//            b.search(obj);
//
//        } else {
//
//            
//
//                workers_caps obj = new workers_caps();
//                workers_cont b = new workers_cont();
//                obj.setSearch(txt_search.getText());
//                b.search_code(obj);
//            
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        workers_caps obj = new workers_caps();
        workers_cont b = new workers_cont();
        obj.setSearch(txt_search.getText());
        b.search(obj);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
 if (radio_name.isSelected()) {
            workers_caps obj = new workers_caps();
            workers_cont b = new workers_cont();
            obj.setSearch(txt_search.getText());
            b.search(obj);

        } else {    workers_caps obj = new workers_caps();
                workers_cont b = new workers_cont();
                obj.setSearch(txt_search.getText());
                b.search_code(obj);
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped

       
// TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

    private void txt_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyReleased

        String s=txt_phone.getText();      
char x=s.charAt(s.length()-1);
int a=x;
if(a>=97 && a<=122 || a>=65 && a<=90){
    txt_phone.setBackground(Color.red);
    add_button.setEnabled(false);
   
}else
{
    txt_phone.setBackground(Color.white);
    add_button.setEnabled(true);
//   txt_phone.setEditable(true);
}
      
        
// TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneKeyReleased

    private void txt_salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salaryKeyReleased
        // TODO add your handling code here:
        String s=txt_salary.getText();
        char x=s.charAt(s.length()-1);
        int a=x;
        if(a>=97 && a<=122 || a>=65 && a<=90){
             txt_salary.setBackground(Color.red);
    add_button.setEnabled(false);
   
        }else
        {
            txt_salary.setBackground(Color.white);
    add_button.setEnabled(true);
        }
        int b=Integer.parseInt(s);
        if(b<=0){
             txt_salary.setBackground(Color.red);
    add_button.setEnabled(false);
        }else
        {
            txt_salary.setBackground(Color.white);
    add_button.setEnabled(true);
        }
    }//GEN-LAST:event_txt_salaryKeyReleased

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped

         
// TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void add_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_imageMouseClicked
try { //upload image on label
JFileChooser file = new JFileChooser();
file.showOpenDialog(this);
File f = file.getSelectedFile();
String s = f.getAbsolutePath();
// jTextField1.setText(a);
try {
File image = new File(s);
FileInputStream g = new FileInputStream(f);
ByteArrayOutputStream bos = new ByteArrayOutputStream();
byte buff[] = new byte[6048576];
try {
for (int i; (i = g.read(buff)) != -1;) {
bos.write(buff, 0, i);
}
byte[] image_right = bos.toByteArray();
ImageIcon q = new ImageIcon(image_right);
image_label.setIcon(q); //jlabel
} catch (Exception ex) {
System.out.println(ex);
}
} catch (Exception ex) {
System.out.println(ex);
}
} catch (Exception e) {
System.out.println(e);
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_add_imageMouseClicked

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_DOWN ||evt.getKeyCode() == KeyEvent.VK_UP){
     
      int row = table.getSelectedRow();
        String name = table.getModel().getValueAt(row, 0).toString();
        txt_name.setText(name);
        String phone = table.getModel().getValueAt(row, 1).toString();
        txt_phone.setText(phone);
        String salary = table.getModel().getValueAt(row, 2).toString();
        txt_salary.setText(salary);
        String time = table.getModel().getValueAt(row, 3).toString();
        combo_time.setSelectedItem(time);
        ((JTextField)start_date.getDateEditor().getUiComponent()).setText(table.getValueAt(row, 4).toString());
        String address = table.getModel().getValueAt(row, 5).toString();
        txt_address.setText(address);
        String code = table.getModel().getValueAt(row, 6).toString();
        txt_code.setText(code);
        String notes = table.getModel().getValueAt(row, 7).toString();
        txta_notes.setText(notes);
     
     
     
 } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_tableKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel add_image;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo_time;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_validation;
    private javax.swing.JButton new_button;
    private javax.swing.JRadioButton radio_code;
    private javax.swing.JRadioButton radio_name;
    public static javax.swing.JTable table;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_salary;
    public static javax.swing.JTextField txt_search;
    private javax.swing.JTextArea txta_notes;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
